
var Constants = {
		
	// IMPORTANTE: PARA PRUEBAS, USAR SIEMPRE UNA IP O NOMBRE DE DOMINIO, NUNCA 'LOCALHOST' O '127.0.0.1'
	// SI NO SE HACE ASI, AUTOFIRMA BLOQUEARA LA FIRMA POR SEGURIDAD
	
	/* DESARROLLO */
	
	URL_BASE_APPLET : "http://demo.tgm:8080",

	URL_BASE_SERVICES : "http://demo.tgm:8080"
};